# Generated by Django 6.0.1 on 2026-01-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category_course_difficulty_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='estimated_duration',
            field=models.CharField(default='10 hours', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_bio',
            field=models.TextField(blank=True, default='Professional software engineer with years of experience.'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default='Expert Instructor', max_length=100),
        ),
    ]
