# Generated by Django 6.0.1 on 2026-01-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_time',
            field=models.IntegerField(default=0),
        ),
    ]
